# Color palette: list of all the colors palettes used to draw.
#                each color consists of a quadlet (RGBA).
#                with bit-depth of 8bits (1byte).

paletteIndex: 0
palettes:
  - [[0x00, 0xad, 0xb5, 0xff], [0x22, 0x28, 0x31, 0xff]] # Green-Darkblue   (0) 
  - [[0xf7, 0x77, 0x54, 0xff], [0x58, 0x4b, 0x42, 0xff]] # Orange-Brown     (1)
  - [[0xf7, 0x77, 0x54, 0xff], [0x22, 0x28, 0x31, 0xff]] # Orange-Darkblue  (2)
  - [[0xff, 0xff, 0xff, 0xff], [0x00, 0x00, 0x00, 0xff]] # White-Black      (3)