# Color palette: list of all the colors palettes used to draw.
#                each color consists of a quadlet (RGBA).
#                with bit-depth of 8bits (1byte).

paletteIndex: 2
palettes:
  # Layout of colors:
  #  Foreground, Background
  - [0x00adb5ff, 0x222831ff] # Green-Darkblue
  - [0xf77754ff, 0x584b42ff] # Orange-Brown
  - [0xf77754ff, 0x222831ff] # Orange-Darkblue
  - [0xffffffff, 0x000000ff] # White-Black